name: FlavorHive Infra Code Scanning

on:
  push:
    branches: [main, integration, release/*]
  pull_request:
    branches: [main, integration, release/*]

jobs:
  tfsec-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup tfsec
        uses: aquasecurity/tfsec-action@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tfsec scan
        run: tfsec .

  checkov-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov scan
        run: checkov -d . --compact
